<?php
include("../template/header.php");
include("../template/topbar.php");
include("../pages/banner.php");
include("../pages/category.php");
include("../pages/index-product.php");
include("../pages/featured.php");
include("../pages/deal-of-the-week.php");
//include("../pages/partners.php");
include("../template/footer.php");
?>